workflows:
  default-workflow:
    name: Generate Flutter structure
    environment:
      flutter: stable
    scripts:
      - name: Create Flutter project
        script: |
          flutter create .
      - name: Get packages
        script: |
          flutter pub get
    artifacts:
      - build/**
